version: "3.9"

services:
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - gunicorn
      - megano.wsgi:application
      - --bind
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200K"
    volumes:
      - ./megano/database:/app2/database