# Generated by Django 4.2 on 2023-08-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        default="app_users/CatalogItem/default.png",
                        upload_to="app_users/CatalogItem/",
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        default="Just an image", max_length=128, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.CreateModel(
            name="SalesItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currentPage", models.IntegerField(default=1)),
                ("lastPage", models.IntegerField(default=1)),
                ("items", models.ManyToManyField(blank=True, to="product.product")),
            ],
            options={
                "verbose_name": "SalesItem",
                "verbose_name_plural": "SalesItem's",
            },
        ),
        migrations.CreateModel(
            name="CatalogItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalogitems_image",
                        to="catalog.image",
                        verbose_name="Image",
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(blank=True, to="catalog.catalogitems"),
                ),
            ],
            options={
                "verbose_name": "CatalogItems",
                "verbose_name_plural": "CatalogItems's",
            },
        ),
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currentPage", models.IntegerField(default=1)),
                ("lastPage", models.IntegerField(default=1)),
                ("items", models.ManyToManyField(blank=True, to="product.product")),
            ],
            options={
                "verbose_name": "CatalogItem",
                "verbose_name_plural": "CatalogItem's",
            },
        ),
    ]
