# Generated by Django 4.2 on 2023-08-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1.01, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="salePrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=1.01, max_digits=10, null=True
            ),
        ),
    ]
