# Generated by Django 4.2 on 2023-08-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=128, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("text", models.TextField(blank=True, max_length=512, null=True)),
                ("rate", models.IntegerField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
